version: '3'
services:
    api-test:
        build: ./src/back
        command: sh -c "npm run test"
        environment:
            SECRET_FILES_EXTERNAL_API_URL: "${SECRET_FILES_EXTERNAL_API_URL}"
            SECRET_FILES_EXTERNAL_API_BEARER_TOKEN: "${SECRET_FILES_EXTERNAL_API_BEARER_TOKEN}"
            PORT: "${API_EXTERNAL_PORT}"
        ports:
            - ${API_EXTERNAL_PORT}:${API_EXTERNAL_PORT}
    
    web-test:
        build:
            context: ./src/front
            args:
                REACT_APP_API_URL: "http://api:${API_EXTERNAL_PORT}"
        command: sh -c "npm run test"
        ports:
            - 3000:3000